name: EosMcPlugin
version: 0.0.1
main: io.github.leordev.EosMcPlugin

commands:
  dump:
    description: Dump EOS Items
    usage: /dump
  eosacc:
    description: Set EOS Account
    usage: /eosacc <account>
  deposit:
    description: Deposit items to Blockchain
    usage: /deposit
    aliases: [dp]
